// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plc.proto

package plc_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type S7CpuInfo struct {
	ModuleTypeName       string   `protobuf:"bytes,1,opt,name=module_type_name,json=moduleTypeName,proto3" json:"module_type_name,omitempty"`
	SerialNumber         string   `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	AsName               string   `protobuf:"bytes,3,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	Copyright            string   `protobuf:"bytes,4,opt,name=copyright,proto3" json:"copyright,omitempty"`
	ModuleName           string   `protobuf:"bytes,5,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S7CpuInfo) Reset()         { *m = S7CpuInfo{} }
func (m *S7CpuInfo) String() string { return proto.CompactTextString(m) }
func (*S7CpuInfo) ProtoMessage()    {}
func (*S7CpuInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{0}
}

func (m *S7CpuInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S7CpuInfo.Unmarshal(m, b)
}
func (m *S7CpuInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S7CpuInfo.Marshal(b, m, deterministic)
}
func (m *S7CpuInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S7CpuInfo.Merge(m, src)
}
func (m *S7CpuInfo) XXX_Size() int {
	return xxx_messageInfo_S7CpuInfo.Size(m)
}
func (m *S7CpuInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S7CpuInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S7CpuInfo proto.InternalMessageInfo

func (m *S7CpuInfo) GetModuleTypeName() string {
	if m != nil {
		return m.ModuleTypeName
	}
	return ""
}

func (m *S7CpuInfo) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *S7CpuInfo) GetAsName() string {
	if m != nil {
		return m.AsName
	}
	return ""
}

func (m *S7CpuInfo) GetCopyright() string {
	if m != nil {
		return m.Copyright
	}
	return ""
}

func (m *S7CpuInfo) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

type Plc struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Rack                 uint32   `protobuf:"varint,2,opt,name=rack,proto3" json:"rack,omitempty"`
	Slot                 uint32   `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plc) Reset()         { *m = Plc{} }
func (m *Plc) String() string { return proto.CompactTextString(m) }
func (*Plc) ProtoMessage()    {}
func (*Plc) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{1}
}

func (m *Plc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plc.Unmarshal(m, b)
}
func (m *Plc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plc.Marshal(b, m, deterministic)
}
func (m *Plc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plc.Merge(m, src)
}
func (m *Plc) XXX_Size() int {
	return xxx_messageInfo_Plc.Size(m)
}
func (m *Plc) XXX_DiscardUnknown() {
	xxx_messageInfo_Plc.DiscardUnknown(m)
}

var xxx_messageInfo_Plc proto.InternalMessageInfo

func (m *Plc) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Plc) GetRack() uint32 {
	if m != nil {
		return m.Rack
	}
	return 0
}

func (m *Plc) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *Plc) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Tag struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Dt      string `protobuf:"bytes,2,opt,name=dt,proto3" json:"dt,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Tag_ValueBool
	//	*Tag_ValueInteger
	//	*Tag_ValueUinteger
	//	*Tag_ValueDouble
	//	*Tag_ValueBytes
	//	*Tag_ValueString
	//	*Tag_ValueTimestamp
	//	*Tag_ValueDuration
	Value                isTag_Value `protobuf_oneof:"value"`
	Err                  string      `protobuf:"bytes,11,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{2}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Tag) GetDt() string {
	if m != nil {
		return m.Dt
	}
	return ""
}

type isTag_Value interface {
	isTag_Value()
}

type Tag_ValueBool struct {
	ValueBool bool `protobuf:"varint,3,opt,name=value_bool,json=valueBool,proto3,oneof"`
}

type Tag_ValueInteger struct {
	ValueInteger int64 `protobuf:"varint,4,opt,name=value_integer,json=valueInteger,proto3,oneof"`
}

type Tag_ValueUinteger struct {
	ValueUinteger uint64 `protobuf:"varint,5,opt,name=value_uinteger,json=valueUinteger,proto3,oneof"`
}

type Tag_ValueDouble struct {
	ValueDouble float64 `protobuf:"fixed64,6,opt,name=value_double,json=valueDouble,proto3,oneof"`
}

type Tag_ValueBytes struct {
	ValueBytes []byte `protobuf:"bytes,7,opt,name=value_bytes,json=valueBytes,proto3,oneof"`
}

type Tag_ValueString struct {
	ValueString string `protobuf:"bytes,8,opt,name=value_string,json=valueString,proto3,oneof"`
}

type Tag_ValueTimestamp struct {
	ValueTimestamp *timestamp.Timestamp `protobuf:"bytes,9,opt,name=value_timestamp,json=valueTimestamp,proto3,oneof"`
}

type Tag_ValueDuration struct {
	ValueDuration *duration.Duration `protobuf:"bytes,10,opt,name=value_duration,json=valueDuration,proto3,oneof"`
}

func (*Tag_ValueBool) isTag_Value() {}

func (*Tag_ValueInteger) isTag_Value() {}

func (*Tag_ValueUinteger) isTag_Value() {}

func (*Tag_ValueDouble) isTag_Value() {}

func (*Tag_ValueBytes) isTag_Value() {}

func (*Tag_ValueString) isTag_Value() {}

func (*Tag_ValueTimestamp) isTag_Value() {}

func (*Tag_ValueDuration) isTag_Value() {}

func (m *Tag) GetValue() isTag_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Tag) GetValueBool() bool {
	if x, ok := m.GetValue().(*Tag_ValueBool); ok {
		return x.ValueBool
	}
	return false
}

func (m *Tag) GetValueInteger() int64 {
	if x, ok := m.GetValue().(*Tag_ValueInteger); ok {
		return x.ValueInteger
	}
	return 0
}

func (m *Tag) GetValueUinteger() uint64 {
	if x, ok := m.GetValue().(*Tag_ValueUinteger); ok {
		return x.ValueUinteger
	}
	return 0
}

func (m *Tag) GetValueDouble() float64 {
	if x, ok := m.GetValue().(*Tag_ValueDouble); ok {
		return x.ValueDouble
	}
	return 0
}

func (m *Tag) GetValueBytes() []byte {
	if x, ok := m.GetValue().(*Tag_ValueBytes); ok {
		return x.ValueBytes
	}
	return nil
}

func (m *Tag) GetValueString() string {
	if x, ok := m.GetValue().(*Tag_ValueString); ok {
		return x.ValueString
	}
	return ""
}

func (m *Tag) GetValueTimestamp() *timestamp.Timestamp {
	if x, ok := m.GetValue().(*Tag_ValueTimestamp); ok {
		return x.ValueTimestamp
	}
	return nil
}

func (m *Tag) GetValueDuration() *duration.Duration {
	if x, ok := m.GetValue().(*Tag_ValueDuration); ok {
		return x.ValueDuration
	}
	return nil
}

func (m *Tag) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Tag) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Tag_ValueBool)(nil),
		(*Tag_ValueInteger)(nil),
		(*Tag_ValueUinteger)(nil),
		(*Tag_ValueDouble)(nil),
		(*Tag_ValueBytes)(nil),
		(*Tag_ValueString)(nil),
		(*Tag_ValueTimestamp)(nil),
		(*Tag_ValueDuration)(nil),
	}
}

type PlcCon struct {
	Tags                 map[string]*Tag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PlcCon) Reset()         { *m = PlcCon{} }
func (m *PlcCon) String() string { return proto.CompactTextString(m) }
func (*PlcCon) ProtoMessage()    {}
func (*PlcCon) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{3}
}

func (m *PlcCon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlcCon.Unmarshal(m, b)
}
func (m *PlcCon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlcCon.Marshal(b, m, deterministic)
}
func (m *PlcCon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlcCon.Merge(m, src)
}
func (m *PlcCon) XXX_Size() int {
	return xxx_messageInfo_PlcCon.Size(m)
}
func (m *PlcCon) XXX_DiscardUnknown() {
	xxx_messageInfo_PlcCon.DiscardUnknown(m)
}

var xxx_messageInfo_PlcCon proto.InternalMessageInfo

func (m *PlcCon) GetTags() map[string]*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Model struct {
	// Use tag in here, address is an express like PLC1.current in equipment tag slot
	Equipments           map[string]*Tag    `protobuf:"bytes,1,rep,name=equipments,proto3" json:"equipments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Plcs                 map[string]*PlcCon `protobuf:"bytes,2,rep,name=plcs,proto3" json:"plcs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{4}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetEquipments() map[string]*Tag {
	if m != nil {
		return m.Equipments
	}
	return nil
}

func (m *Model) GetPlcs() map[string]*PlcCon {
	if m != nil {
		return m.Plcs
	}
	return nil
}

type RWResult struct {
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RWResult) Reset()         { *m = RWResult{} }
func (m *RWResult) String() string { return proto.CompactTextString(m) }
func (*RWResult) ProtoMessage()    {}
func (*RWResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{5}
}

func (m *RWResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RWResult.Unmarshal(m, b)
}
func (m *RWResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RWResult.Marshal(b, m, deterministic)
}
func (m *RWResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWResult.Merge(m, src)
}
func (m *RWResult) XXX_Size() int {
	return xxx_messageInfo_RWResult.Size(m)
}
func (m *RWResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RWResult.DiscardUnknown(m)
}

var xxx_messageInfo_RWResult proto.InternalMessageInfo

func (m *RWResult) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type RWReq struct {
	Plc                  *Plc     `protobuf:"bytes,1,opt,name=plc,proto3" json:"plc,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RWReq) Reset()         { *m = RWReq{} }
func (m *RWReq) String() string { return proto.CompactTextString(m) }
func (*RWReq) ProtoMessage()    {}
func (*RWReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{6}
}

func (m *RWReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RWReq.Unmarshal(m, b)
}
func (m *RWReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RWReq.Marshal(b, m, deterministic)
}
func (m *RWReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWReq.Merge(m, src)
}
func (m *RWReq) XXX_Size() int {
	return xxx_messageInfo_RWReq.Size(m)
}
func (m *RWReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RWReq.DiscardUnknown(m)
}

var xxx_messageInfo_RWReq proto.InternalMessageInfo

func (m *RWReq) GetPlc() *Plc {
	if m != nil {
		return m.Plc
	}
	return nil
}

func (m *RWReq) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*S7CpuInfo)(nil), "plc_api.S7CpuInfo")
	proto.RegisterType((*Plc)(nil), "plc_api.Plc")
	proto.RegisterType((*Tag)(nil), "plc_api.Tag")
	proto.RegisterType((*PlcCon)(nil), "plc_api.PlcCon")
	proto.RegisterMapType((map[string]*Tag)(nil), "plc_api.PlcCon.TagsEntry")
	proto.RegisterType((*Model)(nil), "plc_api.Model")
	proto.RegisterMapType((map[string]*Tag)(nil), "plc_api.Model.EquipmentsEntry")
	proto.RegisterMapType((map[string]*PlcCon)(nil), "plc_api.Model.PlcsEntry")
	proto.RegisterType((*RWResult)(nil), "plc_api.RWResult")
	proto.RegisterType((*RWReq)(nil), "plc_api.RWReq")
}

func init() { proto.RegisterFile("plc.proto", fileDescriptor_a0a6ab4644bfacb6) }

var fileDescriptor_a0a6ab4644bfacb6 = []byte{
	// 709 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xeb, 0x44,
	0x14, 0xb6, 0xe3, 0xfc, 0xf9, 0xe4, 0xa7, 0x97, 0xd9, 0x60, 0x2c, 0xd4, 0x1b, 0x7c, 0x75, 0x45,
	0x16, 0x25, 0xad, 0xca, 0x02, 0xc4, 0x82, 0x45, 0xda, 0x88, 0x54, 0x88, 0x2a, 0x9a, 0xa6, 0xea,
	0x32, 0x9a, 0xd8, 0x53, 0xd7, 0xea, 0xc4, 0xe3, 0xda, 0x63, 0xa4, 0x6c, 0x78, 0x02, 0x1e, 0x81,
	0xa7, 0x80, 0x17, 0x44, 0x73, 0xc6, 0x76, 0x9b, 0x80, 0x04, 0xba, 0xbb, 0x33, 0xdf, 0xf9, 0xce,
	0x77, 0xbe, 0x33, 0x73, 0x6c, 0x70, 0x33, 0x11, 0xce, 0xb2, 0x5c, 0x2a, 0x49, 0x7a, 0x99, 0x08,
	0x37, 0x2c, 0x4b, 0xfc, 0xf7, 0xb1, 0x94, 0xb1, 0xe0, 0xe7, 0x08, 0x6f, 0xcb, 0xc7, 0x73, 0x95,
	0xec, 0x78, 0xa1, 0xd8, 0x2e, 0x33, 0x4c, 0xff, 0xf4, 0x98, 0x10, 0x95, 0x39, 0x53, 0x89, 0x4c,
	0x4d, 0x3e, 0xf8, 0xd3, 0x06, 0xf7, 0xee, 0xbb, 0xab, 0xac, 0xbc, 0x49, 0x1f, 0x25, 0x99, 0xc2,
	0xbb, 0x9d, 0x8c, 0x4a, 0xc1, 0x37, 0x6a, 0x9f, 0xf1, 0x4d, 0xca, 0x76, 0xdc, 0xb3, 0x27, 0xf6,
	0xd4, 0xa5, 0x63, 0x83, 0xaf, 0xf7, 0x19, 0xbf, 0x65, 0x3b, 0x4e, 0x3e, 0xc0, 0xa8, 0xe0, 0x79,
	0xc2, 0xc4, 0x26, 0x2d, 0x77, 0x5b, 0x9e, 0x7b, 0x2d, 0xa4, 0x0d, 0x0d, 0x78, 0x8b, 0x18, 0xf9,
	0x1c, 0x7a, 0xac, 0x30, 0x2a, 0x0e, 0xa6, 0xbb, 0xac, 0xc0, 0xea, 0x2f, 0xc1, 0x0d, 0x65, 0xb6,
	0xcf, 0x93, 0xf8, 0x49, 0x79, 0x6d, 0x4c, 0xbd, 0x02, 0xe4, 0x3d, 0x0c, 0x2a, 0x17, 0x58, 0xda,
	0xc1, 0x3c, 0x18, 0x48, 0x97, 0x07, 0xf7, 0xe0, 0xac, 0x44, 0x48, 0x08, 0xb4, 0x9f, 0x64, 0xa1,
	0x2a, 0x87, 0x18, 0x6b, 0x2c, 0x67, 0xe1, 0x33, 0xda, 0x19, 0x51, 0x8c, 0x35, 0x56, 0x08, 0xa9,
	0xd0, 0xc3, 0x88, 0x62, 0xac, 0xb1, 0x4c, 0xe6, 0xa6, 0xf9, 0x88, 0x62, 0x1c, 0xfc, 0xe5, 0x80,
	0xb3, 0x66, 0x31, 0xf1, 0xa0, 0xc7, 0xa2, 0x28, 0xe7, 0x45, 0x51, 0x49, 0xd7, 0x47, 0x32, 0x86,
	0x56, 0xa4, 0xaa, 0x51, 0x5b, 0x91, 0x76, 0x0a, 0xbf, 0x32, 0x51, 0xf2, 0xcd, 0x56, 0x4a, 0x81,
	0xfa, 0xfd, 0xa5, 0x45, 0x5d, 0xc4, 0xe6, 0x52, 0x0a, 0xf2, 0x11, 0x46, 0x86, 0x90, 0xa4, 0x8a,
	0xc7, 0x3c, 0xc7, 0x7e, 0xce, 0xd2, 0xa2, 0x43, 0x84, 0x6f, 0x0c, 0x4a, 0xbe, 0x86, 0xb1, 0xa1,
	0x95, 0x35, 0x4f, 0x0f, 0xdd, 0x5e, 0x5a, 0xd4, 0x94, 0xdf, 0x57, 0x30, 0xf9, 0x00, 0xa6, 0x70,
	0x13, 0xc9, 0x72, 0x2b, 0xb8, 0xd7, 0x9d, 0xd8, 0x53, 0x7b, 0x69, 0xd1, 0x01, 0xa2, 0xd7, 0x08,
	0x92, 0xaf, 0x60, 0x50, 0xb9, 0xda, 0x2b, 0x5e, 0x78, 0xbd, 0x89, 0x3d, 0x1d, 0x2e, 0x2d, 0x6a,
	0xac, 0xce, 0x35, 0xf6, 0xaa, 0x53, 0xa8, 0x3c, 0x49, 0x63, 0xaf, 0xaf, 0x47, 0x6a, 0x74, 0xee,
	0x10, 0x24, 0x0b, 0x38, 0x31, 0xa4, 0x66, 0xa9, 0x3c, 0x77, 0x62, 0x4f, 0x07, 0x97, 0xfe, 0xcc,
	0x6c, 0xd5, 0xac, 0xde, 0xaa, 0xd9, 0xba, 0x66, 0x2c, 0x2d, 0x6a, 0x46, 0x69, 0x10, 0x32, 0xaf,
	0x87, 0xab, 0x57, 0xcf, 0x03, 0x54, 0xf9, 0xe2, 0x1f, 0x2a, 0xd7, 0x15, 0xa1, 0x99, 0xbb, 0x06,
	0xc8, 0x3b, 0x70, 0x78, 0x9e, 0x7b, 0x03, 0xbc, 0x79, 0x1d, 0xce, 0x7b, 0xd0, 0x41, 0x4a, 0xf0,
	0x1b, 0x74, 0x57, 0x22, 0xbc, 0x92, 0x29, 0xf9, 0x06, 0xda, 0x8a, 0xc5, 0xfa, 0xd1, 0x1c, 0x94,
	0xaf, 0x3e, 0x92, 0x99, 0x49, 0xcf, 0xd6, 0x2c, 0x2e, 0x16, 0xa9, 0xca, 0xf7, 0x14, 0x69, 0xfe,
	0x02, 0xdc, 0x06, 0xd2, 0x0d, 0x9e, 0xf9, 0xbe, 0x7a, 0x6f, 0x1d, 0x92, 0xa0, 0x6a, 0x80, 0xcf,
	0x3d, 0xb8, 0x1c, 0x36, 0x72, 0x6b, 0x16, 0x53, 0x93, 0xfa, 0xa1, 0xf5, 0xbd, 0x1d, 0xfc, 0xde,
	0x82, 0xce, 0x2f, 0x32, 0xe2, 0x82, 0xfc, 0x08, 0xc0, 0x5f, 0xca, 0x24, 0xdb, 0xf1, 0x54, 0xd5,
	0x2e, 0x4e, 0x9b, 0x32, 0xe4, 0xcc, 0x16, 0x0d, 0xc1, 0x58, 0x79, 0x53, 0x41, 0xce, 0xa0, 0x9d,
	0x89, 0xb0, 0xf0, 0x5a, 0x58, 0xe9, 0x1d, 0x55, 0xae, 0x44, 0x58, 0xdb, 0xd7, 0x2c, 0xff, 0x67,
	0x38, 0x39, 0x12, 0xfb, 0xf4, 0x21, 0xfc, 0x25, 0xb8, 0x8d, 0xfe, 0xbf, 0xc8, 0x7c, 0x3c, 0x94,
	0x39, 0x39, 0xba, 0xda, 0xb7, 0xd7, 0x71, 0x06, 0x7d, 0xfa, 0x40, 0x79, 0x51, 0x0a, 0x45, 0x26,
	0xd5, 0x83, 0x98, 0x81, 0x0e, 0x9b, 0x63, 0x26, 0xb8, 0x81, 0x8e, 0x66, 0xbf, 0x90, 0x53, 0x70,
	0x32, 0x11, 0x62, 0xcf, 0xb7, 0xcc, 0x95, 0x08, 0xa9, 0x4e, 0xfc, 0xb7, 0xd4, 0xe5, 0x1f, 0x36,
	0x74, 0x34, 0xfd, 0x81, 0x5c, 0x00, 0xfc, 0xc4, 0x55, 0xfd, 0x4f, 0x3b, 0x10, 0xf3, 0x49, 0x73,
	0x6a, 0xfe, 0x7a, 0x81, 0x45, 0xce, 0xa1, 0x4f, 0x39, 0x8b, 0xf4, 0x3a, 0x90, 0x71, 0xc3, 0x40,
	0x67, 0xfe, 0x67, 0x07, 0x67, 0x3d, 0x57, 0x60, 0x91, 0x0b, 0x70, 0x1f, 0xf2, 0x44, 0xf1, 0xff,
	0x5d, 0xb1, 0xed, 0xe2, 0x96, 0x7f, 0xfb, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x8f, 0x3e,
	0xe9, 0xc6, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlcRWClient is the client API for PlcRW service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlcRWClient interface {
	GetCpuInfo(ctx context.Context, in *Plc, opts ...grpc.CallOption) (*S7CpuInfo, error)
	ReadTags(ctx context.Context, in *RWReq, opts ...grpc.CallOption) (*RWResult, error)
	WriteTags(ctx context.Context, in *RWReq, opts ...grpc.CallOption) (*RWResult, error)
}

type plcRWClient struct {
	cc *grpc.ClientConn
}

func NewPlcRWClient(cc *grpc.ClientConn) PlcRWClient {
	return &plcRWClient{cc}
}

func (c *plcRWClient) GetCpuInfo(ctx context.Context, in *Plc, opts ...grpc.CallOption) (*S7CpuInfo, error) {
	out := new(S7CpuInfo)
	err := c.cc.Invoke(ctx, "/plc_api.PlcRW/GetCpuInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plcRWClient) ReadTags(ctx context.Context, in *RWReq, opts ...grpc.CallOption) (*RWResult, error) {
	out := new(RWResult)
	err := c.cc.Invoke(ctx, "/plc_api.PlcRW/ReadTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plcRWClient) WriteTags(ctx context.Context, in *RWReq, opts ...grpc.CallOption) (*RWResult, error) {
	out := new(RWResult)
	err := c.cc.Invoke(ctx, "/plc_api.PlcRW/WriteTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlcRWServer is the server API for PlcRW service.
type PlcRWServer interface {
	GetCpuInfo(context.Context, *Plc) (*S7CpuInfo, error)
	ReadTags(context.Context, *RWReq) (*RWResult, error)
	WriteTags(context.Context, *RWReq) (*RWResult, error)
}

// UnimplementedPlcRWServer can be embedded to have forward compatible implementations.
type UnimplementedPlcRWServer struct {
}

func (*UnimplementedPlcRWServer) GetCpuInfo(ctx context.Context, req *Plc) (*S7CpuInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCpuInfo not implemented")
}
func (*UnimplementedPlcRWServer) ReadTags(ctx context.Context, req *RWReq) (*RWResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTags not implemented")
}
func (*UnimplementedPlcRWServer) WriteTags(ctx context.Context, req *RWReq) (*RWResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteTags not implemented")
}

func RegisterPlcRWServer(s *grpc.Server, srv PlcRWServer) {
	s.RegisterService(&_PlcRW_serviceDesc, srv)
}

func _PlcRW_GetCpuInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlcRWServer).GetCpuInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plc_api.PlcRW/GetCpuInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlcRWServer).GetCpuInfo(ctx, req.(*Plc))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlcRW_ReadTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RWReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlcRWServer).ReadTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plc_api.PlcRW/ReadTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlcRWServer).ReadTags(ctx, req.(*RWReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlcRW_WriteTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RWReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlcRWServer).WriteTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plc_api.PlcRW/WriteTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlcRWServer).WriteTags(ctx, req.(*RWReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlcRW_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plc_api.PlcRW",
	HandlerType: (*PlcRWServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCpuInfo",
			Handler:    _PlcRW_GetCpuInfo_Handler,
		},
		{
			MethodName: "ReadTags",
			Handler:    _PlcRW_ReadTags_Handler,
		},
		{
			MethodName: "WriteTags",
			Handler:    _PlcRW_WriteTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plc.proto",
}
