// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plc.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataType int32

const (
	DataType_BOOL DataType = 0
	DataType_INT  DataType = 1
	DataType_DINT DataType = 2
	DataType_REAL DataType = 3
)

var DataType_name = map[int32]string{
	0: "BOOL",
	1: "INT",
	2: "DINT",
	3: "REAL",
}

var DataType_value = map[string]int32{
	"BOOL": 0,
	"INT":  1,
	"DINT": 2,
	"REAL": 3,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{0}
}

type S7CpuInfo struct {
	ModuleTypeName       string   `protobuf:"bytes,1,opt,name=module_type_name,json=moduleTypeName,proto3" json:"module_type_name,omitempty"`
	SerialNumber         string   `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	AsName               string   `protobuf:"bytes,3,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	Copyright            string   `protobuf:"bytes,4,opt,name=copyright,proto3" json:"copyright,omitempty"`
	ModuleName           string   `protobuf:"bytes,5,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S7CpuInfo) Reset()         { *m = S7CpuInfo{} }
func (m *S7CpuInfo) String() string { return proto.CompactTextString(m) }
func (*S7CpuInfo) ProtoMessage()    {}
func (*S7CpuInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{0}
}

func (m *S7CpuInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S7CpuInfo.Unmarshal(m, b)
}
func (m *S7CpuInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S7CpuInfo.Marshal(b, m, deterministic)
}
func (m *S7CpuInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S7CpuInfo.Merge(m, src)
}
func (m *S7CpuInfo) XXX_Size() int {
	return xxx_messageInfo_S7CpuInfo.Size(m)
}
func (m *S7CpuInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S7CpuInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S7CpuInfo proto.InternalMessageInfo

func (m *S7CpuInfo) GetModuleTypeName() string {
	if m != nil {
		return m.ModuleTypeName
	}
	return ""
}

func (m *S7CpuInfo) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *S7CpuInfo) GetAsName() string {
	if m != nil {
		return m.AsName
	}
	return ""
}

func (m *S7CpuInfo) GetCopyright() string {
	if m != nil {
		return m.Copyright
	}
	return ""
}

func (m *S7CpuInfo) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

type Plc struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Rack                 uint32   `protobuf:"varint,2,opt,name=rack,proto3" json:"rack,omitempty"`
	Slot                 uint32   `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plc) Reset()         { *m = Plc{} }
func (m *Plc) String() string { return proto.CompactTextString(m) }
func (*Plc) ProtoMessage()    {}
func (*Plc) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{1}
}

func (m *Plc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plc.Unmarshal(m, b)
}
func (m *Plc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plc.Marshal(b, m, deterministic)
}
func (m *Plc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plc.Merge(m, src)
}
func (m *Plc) XXX_Size() int {
	return xxx_messageInfo_Plc.Size(m)
}
func (m *Plc) XXX_DiscardUnknown() {
	xxx_messageInfo_Plc.DiscardUnknown(m)
}

var xxx_messageInfo_Plc proto.InternalMessageInfo

func (m *Plc) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Plc) GetRack() uint32 {
	if m != nil {
		return m.Rack
	}
	return 0
}

func (m *Plc) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

type Tag struct {
	Address string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Dt      DataType `protobuf:"varint,2,opt,name=dt,proto3,enum=pb.DataType" json:"dt,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Tag_ValueBool
	//	*Tag_ValueInt
	//	*Tag_ValueFloat
	Value                isTag_Value `protobuf_oneof:"value"`
	Err                  string      `protobuf:"bytes,6,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{2}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Tag) GetDt() DataType {
	if m != nil {
		return m.Dt
	}
	return DataType_BOOL
}

type isTag_Value interface {
	isTag_Value()
}

type Tag_ValueBool struct {
	ValueBool bool `protobuf:"varint,3,opt,name=value_bool,json=valueBool,proto3,oneof"`
}

type Tag_ValueInt struct {
	ValueInt int32 `protobuf:"varint,4,opt,name=value_int,json=valueInt,proto3,oneof"`
}

type Tag_ValueFloat struct {
	ValueFloat float32 `protobuf:"fixed32,5,opt,name=value_float,json=valueFloat,proto3,oneof"`
}

func (*Tag_ValueBool) isTag_Value() {}

func (*Tag_ValueInt) isTag_Value() {}

func (*Tag_ValueFloat) isTag_Value() {}

func (m *Tag) GetValue() isTag_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Tag) GetValueBool() bool {
	if x, ok := m.GetValue().(*Tag_ValueBool); ok {
		return x.ValueBool
	}
	return false
}

func (m *Tag) GetValueInt() int32 {
	if x, ok := m.GetValue().(*Tag_ValueInt); ok {
		return x.ValueInt
	}
	return 0
}

func (m *Tag) GetValueFloat() float32 {
	if x, ok := m.GetValue().(*Tag_ValueFloat); ok {
		return x.ValueFloat
	}
	return 0
}

func (m *Tag) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Tag) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Tag_ValueBool)(nil),
		(*Tag_ValueInt)(nil),
		(*Tag_ValueFloat)(nil),
	}
}

type RWResult struct {
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RWResult) Reset()         { *m = RWResult{} }
func (m *RWResult) String() string { return proto.CompactTextString(m) }
func (*RWResult) ProtoMessage()    {}
func (*RWResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{3}
}

func (m *RWResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RWResult.Unmarshal(m, b)
}
func (m *RWResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RWResult.Marshal(b, m, deterministic)
}
func (m *RWResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWResult.Merge(m, src)
}
func (m *RWResult) XXX_Size() int {
	return xxx_messageInfo_RWResult.Size(m)
}
func (m *RWResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RWResult.DiscardUnknown(m)
}

var xxx_messageInfo_RWResult proto.InternalMessageInfo

func (m *RWResult) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type RWReq struct {
	Plc                  *Plc     `protobuf:"bytes,1,opt,name=plc,proto3" json:"plc,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RWReq) Reset()         { *m = RWReq{} }
func (m *RWReq) String() string { return proto.CompactTextString(m) }
func (*RWReq) ProtoMessage()    {}
func (*RWReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a6ab4644bfacb6, []int{4}
}

func (m *RWReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RWReq.Unmarshal(m, b)
}
func (m *RWReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RWReq.Marshal(b, m, deterministic)
}
func (m *RWReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWReq.Merge(m, src)
}
func (m *RWReq) XXX_Size() int {
	return xxx_messageInfo_RWReq.Size(m)
}
func (m *RWReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RWReq.DiscardUnknown(m)
}

var xxx_messageInfo_RWReq proto.InternalMessageInfo

func (m *RWReq) GetPlc() *Plc {
	if m != nil {
		return m.Plc
	}
	return nil
}

func (m *RWReq) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.DataType", DataType_name, DataType_value)
	proto.RegisterType((*S7CpuInfo)(nil), "pb.S7CpuInfo")
	proto.RegisterType((*Plc)(nil), "pb.Plc")
	proto.RegisterType((*Tag)(nil), "pb.Tag")
	proto.RegisterType((*RWResult)(nil), "pb.RWResult")
	proto.RegisterType((*RWReq)(nil), "pb.RWReq")
}

func init() { proto.RegisterFile("plc.proto", fileDescriptor_a0a6ab4644bfacb6) }

var fileDescriptor_a0a6ab4644bfacb6 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0x1d, 0x3b, 0x69, 0xec, 0x49, 0x52, 0x45, 0x73, 0xc1, 0x94, 0x22, 0x8a, 0x11, 0x25,
	0xe2, 0x10, 0x89, 0x70, 0xe0, 0x88, 0x1a, 0x0a, 0x24, 0x52, 0x95, 0x56, 0x8b, 0xa5, 0x1c, 0xad,
	0xb5, 0xbd, 0x75, 0x23, 0x36, 0x5e, 0xe3, 0x5d, 0x23, 0xe5, 0xc2, 0x8f, 0xe2, 0xca, 0x9f, 0x43,
	0x3b, 0x8e, 0xe1, 0x06, 0xb7, 0xe7, 0x6f, 0x66, 0x9f, 0xdf, 0x93, 0x06, 0x82, 0x4a, 0x66, 0xf3,
	0xaa, 0x56, 0x46, 0xa1, 0x5b, 0xa5, 0xd1, 0xcf, 0x1e, 0x04, 0x5f, 0xde, 0x7d, 0xa8, 0x9a, 0x75,
	0x79, 0xaf, 0x70, 0x06, 0xd3, 0xbd, 0xca, 0x1b, 0x29, 0x12, 0x73, 0xa8, 0x44, 0x52, 0xf2, 0xbd,
	0x08, 0x7b, 0x17, 0xbd, 0x59, 0xc0, 0x4e, 0x5b, 0x1e, 0x1f, 0x2a, 0xb1, 0xe1, 0x7b, 0x81, 0x2f,
	0x60, 0xa2, 0x45, 0xbd, 0xe3, 0x32, 0x29, 0x9b, 0x7d, 0x2a, 0xea, 0xd0, 0xa5, 0xb5, 0x71, 0x0b,
	0x37, 0xc4, 0xf0, 0x11, 0x0c, 0xb9, 0x6e, 0x5d, 0x3c, 0x1a, 0x9f, 0x70, 0x4d, 0xaf, 0xcf, 0x21,
	0xc8, 0x54, 0x75, 0xa8, 0x77, 0xc5, 0x83, 0x09, 0xfb, 0x34, 0xfa, 0x0b, 0xf0, 0x19, 0x8c, 0x8e,
	0x29, 0xe8, 0xe9, 0x80, 0xe6, 0xd0, 0x22, 0xfb, 0x3c, 0xba, 0x02, 0xef, 0x4e, 0x66, 0x88, 0xd0,
	0x7f, 0x50, 0xda, 0x1c, 0x13, 0x92, 0xb6, 0xac, 0xe6, 0xd9, 0x57, 0x8a, 0x33, 0x61, 0xa4, 0x2d,
	0xd3, 0x52, 0x19, 0xca, 0x30, 0x61, 0xa4, 0xa3, 0x5f, 0x3d, 0xf0, 0x62, 0x5e, 0x60, 0x08, 0x43,
	0x9e, 0xe7, 0xb5, 0xd0, 0xfa, 0x68, 0xd3, 0x7d, 0xe2, 0x39, 0xb8, 0xb9, 0x21, 0x9f, 0xd3, 0xc5,
	0x78, 0x5e, 0xa5, 0xf3, 0x6b, 0x6e, 0xb8, 0xed, 0xcf, 0xdc, 0xdc, 0x66, 0x84, 0xef, 0x5c, 0x36,
	0x22, 0x49, 0x95, 0x92, 0xe4, 0xec, 0xaf, 0x1c, 0x16, 0x10, 0x5b, 0x2a, 0x25, 0xf1, 0x29, 0xb4,
	0x1f, 0xc9, 0xae, 0x6c, 0x2b, 0x0e, 0x56, 0x0e, 0xf3, 0x09, 0xad, 0x4b, 0x83, 0xcf, 0x61, 0xd4,
	0x8e, 0xef, 0xa5, 0xe2, 0x86, 0x3a, 0xba, 0x2b, 0x87, 0xb5, 0xa6, 0x9f, 0x2c, 0xc3, 0x29, 0x78,
	0xa2, 0xae, 0xc3, 0x13, 0x8a, 0x65, 0xe5, 0x72, 0x08, 0x03, 0x9a, 0x47, 0xaf, 0xc0, 0x67, 0x5b,
	0x26, 0x74, 0x23, 0x0d, 0x3e, 0x81, 0xbe, 0xe1, 0x85, 0x0e, 0xdd, 0x0b, 0x6f, 0x36, 0x5a, 0x0c,
	0x6d, 0xd2, 0x98, 0x17, 0x8c, 0x60, 0xf4, 0x1e, 0x06, 0x76, 0xf1, 0x1b, 0x3e, 0x06, 0xaf, 0x92,
	0x19, 0x75, 0x3c, 0x2e, 0xdd, 0xc9, 0x8c, 0x59, 0xf6, 0x4f, 0x83, 0xd7, 0x6f, 0xc0, 0xef, 0x7a,
	0xa3, 0x0f, 0xfd, 0xe5, 0xed, 0xed, 0xcd, 0xd4, 0xc1, 0x21, 0x78, 0xeb, 0x4d, 0x3c, 0xed, 0x59,
	0x74, 0x6d, 0x95, 0x6b, 0x15, 0xfb, 0x78, 0x75, 0x33, 0xf5, 0x16, 0x3f, 0x60, 0x60, 0xbd, 0xb7,
	0x78, 0x09, 0xf0, 0x59, 0x98, 0xee, 0xb6, 0xba, 0x9f, 0x9e, 0x4d, 0xac, 0xf8, 0x73, 0x73, 0x91,
	0x83, 0x2f, 0xc1, 0x67, 0x82, 0xe7, 0x31, 0x2f, 0x34, 0x06, 0x76, 0x48, 0x91, 0xcf, 0xc6, 0x9d,
	0xb4, 0x35, 0x23, 0x07, 0x2f, 0x21, 0xd8, 0xd6, 0x3b, 0x23, 0xfe, 0xb3, 0x97, 0x9e, 0xd0, 0x75,
	0xbf, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xd2, 0x67, 0x5b, 0xea, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlcRWClient is the client API for PlcRW service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlcRWClient interface {
	GetCpuInfo(ctx context.Context, in *Plc, opts ...grpc.CallOption) (*S7CpuInfo, error)
	ReadTags(ctx context.Context, in *RWReq, opts ...grpc.CallOption) (*RWResult, error)
	WriteTags(ctx context.Context, in *RWReq, opts ...grpc.CallOption) (*RWResult, error)
}

type plcRWClient struct {
	cc *grpc.ClientConn
}

func NewPlcRWClient(cc *grpc.ClientConn) PlcRWClient {
	return &plcRWClient{cc}
}

func (c *plcRWClient) GetCpuInfo(ctx context.Context, in *Plc, opts ...grpc.CallOption) (*S7CpuInfo, error) {
	out := new(S7CpuInfo)
	err := c.cc.Invoke(ctx, "/pb.PlcRW/GetCpuInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plcRWClient) ReadTags(ctx context.Context, in *RWReq, opts ...grpc.CallOption) (*RWResult, error) {
	out := new(RWResult)
	err := c.cc.Invoke(ctx, "/pb.PlcRW/ReadTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plcRWClient) WriteTags(ctx context.Context, in *RWReq, opts ...grpc.CallOption) (*RWResult, error) {
	out := new(RWResult)
	err := c.cc.Invoke(ctx, "/pb.PlcRW/WriteTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlcRWServer is the server API for PlcRW service.
type PlcRWServer interface {
	GetCpuInfo(context.Context, *Plc) (*S7CpuInfo, error)
	ReadTags(context.Context, *RWReq) (*RWResult, error)
	WriteTags(context.Context, *RWReq) (*RWResult, error)
}

// UnimplementedPlcRWServer can be embedded to have forward compatible implementations.
type UnimplementedPlcRWServer struct {
}

func (*UnimplementedPlcRWServer) GetCpuInfo(ctx context.Context, req *Plc) (*S7CpuInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCpuInfo not implemented")
}
func (*UnimplementedPlcRWServer) ReadTags(ctx context.Context, req *RWReq) (*RWResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTags not implemented")
}
func (*UnimplementedPlcRWServer) WriteTags(ctx context.Context, req *RWReq) (*RWResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteTags not implemented")
}

func RegisterPlcRWServer(s *grpc.Server, srv PlcRWServer) {
	s.RegisterService(&_PlcRW_serviceDesc, srv)
}

func _PlcRW_GetCpuInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlcRWServer).GetCpuInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PlcRW/GetCpuInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlcRWServer).GetCpuInfo(ctx, req.(*Plc))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlcRW_ReadTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RWReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlcRWServer).ReadTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PlcRW/ReadTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlcRWServer).ReadTags(ctx, req.(*RWReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlcRW_WriteTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RWReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlcRWServer).WriteTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PlcRW/WriteTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlcRWServer).WriteTags(ctx, req.(*RWReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlcRW_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PlcRW",
	HandlerType: (*PlcRWServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCpuInfo",
			Handler:    _PlcRW_GetCpuInfo_Handler,
		},
		{
			MethodName: "ReadTags",
			Handler:    _PlcRW_ReadTags_Handler,
		},
		{
			MethodName: "WriteTags",
			Handler:    _PlcRW_WriteTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plc.proto",
}
